### ISSUE TITLE
我是新手，里面有三个子项目，如何运行呢？为什么我编译报错呢？

### ISSUE THREAD

**Issue by Lee-Woo** [yuriyoung/qml-examples#1]
![Snipaste_2024-06-20_10-34-59](https://github.com/yuriyoung/qml-examples/assets/8434228/ee118418-6e8c-4cb2-bfee-4322c9109ed4)

**Comment by yuriyoung** [comment]
代码是在Qt5环境下编译的，Qt6没有做测试。有空我整整Qt6。
